---
driver:
  #name: vagrant
  #customize:
  #  setextradata:
  #    CustomVideoMode1: 1900x600x32
  #customize:
  #  setextradata:
   #   - CustomVideoMode1: 1900x600x32
  name: vagrant
  provider: virtualbox 

       
  #gui: true
  #customize:
   # setextradata:
   #   - CustomVideoMode1: 1900x600x32
    
  # 	p.customize ["setextradata", :id, "CustomVideoMode1", "1900x600x32"]
  #   memory: 3072
  #   cpus: 2

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: bento/centos-7.3

suites:
  - name: default
    run_list:
      - recipe[pet_cookbook::default]
    verifier:
      inspec_tests:
        - test/smoke/default
