create table authorization (Login varchar(30) NOT NULL, KEY(Login), Password varchar(30) NOT NULL, Role varchar(50) NOT NULL, pib TEXT NOT NULL);

INSERT INTO authorization
(
  Login,
  Password,
  Role,
  pib
)
VALUES
(
'Savka',
'q1w2e3r4',
'Administrator',
'Pib'
);

create table Registry (
id 															MEDIUMINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
PasportniDaniTitle											TEXT,
PasportniDani												TEXT,
HistoryNumber    											TEXT,
Age															TEXT,
Address														TEXT,
Proffesional    											TEXT,
Disability													TEXT,
ReceduvyTromboemboliiTitle									TEXT,
ReceduvyTromboembolii   									TEXT,
TromboemboliiAndEstrogens									TEXT,
TromboemboliaSprovokovana									TEXT,
SimeinuiAnamnezTromboembolii								TEXT,
VstanovlennaTrombofilia										TEXT,
SypytniZahvoryvanna											TEXT,
OldMore35													TEXT,
Ogirinna													TEXT,
VagitnistMore3												TEXT,
Kyrinna														TEXT,
VelykiVarikozniVenu											TEXT,
ProvedennaProfTEYdpVagitnosti								TEXT,
ElastychnaKompresia											TEXT,
MedukamentoznaProfilaktuka									TEXT,
MedukamentoznaProfilaktukaNazvaPreperaty					TEXT,
MedukamentoznaProfilaktukaRegymPrujomy						TEXT,
HiryrgichneLikyvanna										TEXT,
TryvalistProvedennoiProfilaktyky							TEXT,
YskladneenaVidProfilaktyku									TEXT,
AkysherskiiAnamnez											TEXT,
DanaVagitnist												TEXT,
DanaVagitnistZaRahynkom  									TEXT,
DaniPologuZaRahynkom										TEXT,
PoperedniPologuZavershulus 									TEXT,
PoperedniPologu												TEXT,
NayavnistGuvyhDitey 										TEXT,
VPerebigDannoiVagitnosti									TEXT,
Vagitnist													TEXT,
NaOblikyVGinochiiKonsyltacii								TEXT,
ZagrozaPereruvannaVagitnosti								TEXT,
ZagrozaPeredchasnuhPologiv									TEXT,
ZagrozaPeredchasnuhPologivP4_1								TEXT,
GestozIPolovunuVagitnosti									TEXT,
InshiPruchynyZnevodnenna									TEXT,
GestozIIPolovunuVagitnosti									TEXT,
GestozIIPolovunuVagitnostiVTermini							TEXT,
VunuknennaTEY												TEXT,
VudTEY														TEXT,
TEYTerminVagitnosti											TEXT,
Bagatovodda													TEXT,
BagatovoddaDiagnostovanoVTerminVagitnosti					TEXT,
MaloVodda													TEXT,
MaloVoddaDiagnostovanoVTerminVagitnosti						TEXT,
DustressPloda												TEXT,
ZatrumkaRozvutkyPloda										TEXT,
NajavnistSustemnoiInfekcii 									TEXT,
PatologiaPlacentu											TEXT,
PatologiaLocalizaciiPlacentu    							TEXT,
PeredchasneVadsharyvannaPlacentu							TEXT,
HiryrgichniVtyrchannaPidChasVagitnosti						TEXT,
TruvalaImmobilizacia										TEXT,
ZavershennaDannoiVagitnosti									TEXT,
ProvedennaProfilaktukuTerapiiTEYPidChasVagitnosti			TEXT,
PokazuDlaProvedennaProfilaktuky								TEXT,
ElastychnaKompresiaPynktVI									TEXT,
MedukamentoznaProfilaktukaPynktVI							TEXT,
MedukamentoznaProfilaktukaPynktVINazvaPreperaty				TEXT,
MedukamentoznaProfilaktukaPynktVIRegymPrujomy				TEXT,
MedukamentoznaProfilaktukaPynktVITerminKoluPruznacheno		TEXT,
HiryrgichneLikyvannaPynktVI									TEXT,
TryvalistProvedennoiProfilaktykyPynktVI						TEXT,
YskladneenaVidProfilaktykuPynktVI 							TEXT,
TerapiyVidminenoZaGodDoPologivPynktVI						TEXT,
PerebigDanuhPologiv											TEXT,
PologuVaginalni												TEXT,
PologuAbdominalni											TEXT,
PokazannaDlaAbdominalnogoRozrodjenna						TEXT,
PoryshennaPologovoiDialnosti								TEXT,
KorekciaAnomaliiPologovoiDialnosti							TEXT,
VuluvNavkoloplodovuhVod										TEXT,
DustressPlodaVPologah										TEXT,
GipotonichnaKrovotecha										TEXT,
AnomaliiPrukriplennaPlacentu								TEXT,
DefektPoslidy												TEXT,
DefektObolonok												TEXT,
AnomaliiPrukriplennaPypovunu								TEXT,
OperatuvnaDopomoga											TEXT,
RozruvuPologovuhShlahiv										TEXT,
EpizoAboPerineotomia										TEXT,
KrovovtrataVPologah											TEXT,
TruvalistPologiv											TEXT,
StanNovonarodgennogoTaNeoPeriodTitleLable					TEXT,
Naroduvsa													TEXT,
PruchunaMertvonarodgenna									TEXT,
ZrilistNovonarodgennogo										TEXT,
ParametruNovonarodgennogo									TEXT,
GipotrofiaPloda												TEXT,
OcinkaZaShkaloyApgar										TEXT,
NovonarodjenuiZVadamuRozvutky								TEXT,
PologovaTravma												TEXT,
SDR															TEXT,
VnytrishnoytrobneInfikyvanna								TEXT,
GemoragichniYskladnenna										TEXT,
Anemia														TEXT,
GiperBilirybinemia											TEXT,
Asfiksia													TEXT,
PoryshennaKardioRespiratornoiAdaptacii						TEXT,
VtrataMasuTila												TEXT,
VitaminKVvedeno												TEXT,
VupusanuiNa													TEXT,
NeonatalnaSmert												TEXT,
PruchunaSmertiZaRezyltatomAytopsii							TEXT,
PislapologovuiPeriod 										TEXT,
PislapologovuiPerebig										TEXT,
ProfilaktukaTerapiaTEYPynktI 								TEXT,
ElastuchnaKompressiaPynktIX				  					TEXT,
MedukamentoznaProfilaktukaPynktIX   						TEXT,
MedukamentoznaProfilaktukaPynktIXNazvaPreparaty				TEXT,
MedukamentoznaProfilaktukaPynktIXRegumPrujomy				TEXT,
MedukamentoznaProfilaktukaPynktIXTerminKoluPruznacheno		TEXT,
HiryrgichneLikyvannaPynktIX									TEXT,
HiryrgichneLikyvannaPynktIXTerminNazvaOperacii				TEXT,
TruvalistProvedenoiProfilaktuktPynktIX						TEXT,
YskladnennaVidProfilaktukyPynktIX 							TEXT,
TromboembolichniYskladnennaPynktIX							TEXT,
TromboembolichniYskladnennaPynktIXVudTey					TEXT,
TromboembolichniYskladnennaPynktIXTerminVunuknenna			TEXT,
TromboembolichniYskladnennaPynktIXTerapiaTEY				TEXT,
MastutPynktIX                       						TEXT,
SubinvolyciaMatkuPynktIX           							TEXT,
EndometrutPynktIX                             				TEXT,
PiznaPologovaKrovotechaPynktIX     							TEXT,
SepsusPynktIX                         						TEXT,
RoshodgennaShvivPynktIX          							TEXT,
InshiPynktIX												TEXT,
HirVtyrchannaVPershi6TugnivPynktIX 							TEXT,
VupuskaDodomyPynktIX               							TEXT,
PerevedennaVInshuiStacionarPynktIX 							TEXT,
ChangeDateRow												TEXT,
WhoChangeRow												TEXT
);
ALTER TABLE Registry ENGINE = MYISAM;
